

CREATE TABLE st_user_master (
  user_id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(30) NOT NULL,
  user_status ENUM('ACTIVE','INACTIVE','TERMINATE') DEFAULT 'ACTIVE',
  created_at DATETIME DEFAULT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE st_user_credit_note_details (
  id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  txn_id INT(10) NOT NULL UNIQUE KEY,
  user_id INT(5),
  credit_amount DOUBLE(10,2)  DEFAULT 0,
  created_at DATETIME DEFAULT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE st_user_debit_note_details (
  id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  txn_id INT(10) NOT NULL UNIQUE KEY,
  user_id INT(5),
  debit_amount DOUBLE(10,2)  DEFAULT 0,
  created_at DATETIME DEFAULT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE st_transaction_master (
  txn_id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ref_txn_id INT(10) NOT NULL UNIQUE KEY,
  txn_type ENUM('CREDIT','DEBIT') DEFAULT NULL,
  txn_status ENUM('INITIATED' , 'FAILED', 'DONE') DEFAULT 'INITIATED'
)ENGINE=INNODB DEFAULT CHARSET=utf8;
